version: '3'

services:
  web:
    build: .
    ports:
      - "34801:34801"
    volumes:
      - .:/app
      - ./public/songs:/app/public/songs
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/taiko
      - REDIS_URL=redis://redis:6379
    command: [ "python", "app.py", "--port", "34801" ]
    networks:
      - app-network

  websocket:
    build: .
    ports:
      - "34802:34802"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/taiko
      - REDIS_URL=redis://redis:6379
    command: python server.py 34802
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=taiko
    networks:
      - app-network

  redis:
    image: redis:6
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./tools/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
    depends_on:
      - web
      - websocket
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo_data: